require("abraxas.default.plugins-setup")
require("abraxas.core.options")
require("abraxas.core.keymaps")
require("abraxas.core.colorscheme")
require("abraxas.default.plugins.comment")
require("abraxas.default.plugins.nvim-tree")
require("abraxas.default.plugins.lualine")
require("abraxas.default.plugins.telescope")
require("abraxas.default.plugins.nvim-cmp")
require("abraxas.default.plugins.lsp.mason")
require("abraxas.default.plugins.lsp.lspconfig")
require("abraxas.default.plugins.lsp.null-ls")
-- require("abraxas.default.plugins.lsp.lsp_signature")
require("abraxas.default.plugins.treesitter")
require("abraxas.default.plugins.gitsigns")
require("abraxas.default.plugins.go-nvim")
require("abraxas.default.plugins.js-ts-nvimlf")
-- require("abraxas.default.plugins.colorizer")
--
